apiVersion: v1
kind: Secret
metadata:
  name: environmentsecrets
type: Opaque
stringData:
  CUSTOM_UPLOAD_TOKEN: "$CUSTOM_UPLOAD_TOKEN"
  CUSTOM_UPLOAD_ACCOUNT_NAME: "$CUSTOM_UPLOAD_ACCOUNT_NAME"
  CUSTOM_UPLOAD_URL: "$CUSTOM_UPLOAD_URL"